---
title: "board games no functions"
embed-resources: true
format: html
editor: visual
execute:
  warning: false
---

## Set-up

```{r}
library(dplyr)
library(echarts4r)
```

```{r}
# First thing - create a new project but make it R package!
# Already wrote code to import data from tidytuesday, I just saved as parquet

# Using board game date from tidyTuesday from '2022-01-25'
# Data comes from BoardGameGeek and xxx
# https://github.com/rfordatascience/tidytuesday/blob/main/data/2022/2022-01-25/readme.md

game_ratings <- arrow::read_parquet("data-raw/game_ratings.parquet")
game_details <- arrow::read_parquet("data-raw/game_details.parquet")

games <- left_join(game_ratings, game_details, by = "id")
```

## Data analysis

```{r}
games |>
    dplyr::mutate(
      # Regex for starts with [ or ends with ]
      boardgamedesigner_clean = stringr::str_remove_all(boardgamedesigner, "^\\[|\\]$|'"),
      # Regex to remove comma before Jr.
      boardgamedesigner_clean = stringr::str_replace_all(boardgamedesigner_clean, ",\\s*(Jr\\.?)", replacement = " \\1")
    ) |>
    tidyr::separate_wider_delim(
      boardgamedesigner_clean,
      delim = ", ",
      names_sep = "",
      too_few = "align_start"
    ) |> 
    tidyr::pivot_longer(starts_with("boardgamedesigner_clean"), values_to = "value", names_to = "colname") |>
    dplyr::count(value, sort = TRUE) |> 
  dplyr::filter(!is.na(value), value !="(Uncredited)") |> 
  dplyr::slice_max(n = 5, order_by = n) |> 
  arrange(n) |> 
e_chart(value) |> 
  e_bar(n) |> e_flip_coords() |> 
  e_tooltip()

games |>
    dplyr::mutate(
      # Regex for starts with [ or ends with ]
      boardgamemechanic_clean = stringr::str_remove_all(boardgamemechanic, "^\\[|\\]$|'"),
      # Regex to remove comma before Jr.
      boardgamemechanic_clean = stringr::str_replace_all(boardgamemechanic_clean, ",\\s*(Jr\\.?)", replacement = " \\1")
    ) |>
    tidyr::separate_wider_delim(
      boardgamemechanic_clean,
      delim = ", ",
      names_sep = "",
      too_few = "align_start"
    ) |> 
    tidyr::pivot_longer(starts_with("boardgamemechanic_clean"), values_to = "value", names_to = "colname") |>
    dplyr::count(value, sort = TRUE) |> 
  dplyr::filter(!is.na(value), value !="(Uncredited)") |> 
  dplyr::slice_max(n = 5, order_by = n) |> 
  arrange(n) |> 
e_chart(value) |> 
  e_bar(n) |> e_flip_coords() |> 
  e_tooltip()

games |> 
    dplyr::mutate(average_category = 
    cut(
    average,
    breaks = c(0, 2, 4, 6, 8, 10),
    labels = c("Extremely annoying game", 
               "Likely won't play this again",
               "Average - slightly boring", 
               "Good - willing to play", 
               "Excellent - always want to play!")
  )) |> 
  dplyr::group_by(average_category) |> 
    dplyr::slice_max(order_by = users_rated, n = 3) |> 
  dplyr::ungroup() |> 
  dplyr::select(name, average_category) |> 
  dplyr::arrange(rev(average_category)) |> 
  gt::gt()
```

