---
title: "board games"
format: html
editor: visual
---

## Set-up

```{r}
library(dplyr)
library(echarts4r)
source("R/categorizeRatings.R")

# First thing - create a new project but make it R package!


# Using board game date from tidyTuesday on '2022-01-25'
# Data comes from BoardGameGeek and xxx
# https://github.com/rfordatascience/tidytuesday/blob/main/data/2022/2022-01-25/readme.md

# I already loaded this data and saved as a parquet file!
game_ratings <- arrow::read_parquet("data-raw/game_ratings.parquet")
game_details <- arrow::read_parquet("data-raw/game_details.parquet")
```

## Data cleaning and recoding

```{r}
# How to deal with NA values in rating? Or with values outside 0 - 10 ? Write unit tests for this then determine expected behavior!!
game_ratings <- game_ratings |>
  dplyr::mutate(average_category = 
    cut(
    average,
    breaks = c(0, 2, 4, 6, 8, 10),
    labels = c("Extremely annoying game", 
               "Likely won't play this again",
               "Average - slightly boring", 
               "Good - willing to play", 
               "Excellent - always want to play!"),
    right = FALSE
  ))

# With the function
# game_ratings <- game_ratings |>
  # dplyr::mutate(average_category = categorizeRatings(average), bayes_average_category = categorizeRatings(bayes_average))
```

## Data analysis

```{r}
game_count <- game_ratings |> group_by(average_category) |> summarise(n = n(), .groups = "drop") |>
  mutate(perc = n / sum(n) * 100)

# Most rated games for each category based on most rated
game_ratings |> 
  dplyr::group_by(average_category) |> 
    dplyr::slice_max(order_by = users_rated, n = 3)

# game_details |> 
#   dplyr::group_by(average_category) |>
#     dplyr::slice_max(order_by = owned, n = 3)


extractTopNGames <- function(df, group_by_this, take_max_of_this, top_n){
  df |> 
  dplyr::group_by({{group_by_this}}) |> 
    dplyr::slice_max(order_by = {{take_max_of_this}}, n = top_n) |> 
    dplyr::ungroup()
}

extractTopNGames(df = game_ratings, group_by_this = average_category, take_max_of_this = users_rated, top_n = 3)
```

## Charts!

```{r}
e <- game_count |> 
e_chart(average_category) |> 
  e_bar(perc) |> e_flip_coords()

createHorizontalBarChart <- function(df, x_axis, y_axis){
  
}

# What to test?
# If the correct x axis is used
# Correct class
# Data on series is correct
# Correct chart type on first series

e$x$mapping$x

df <- data.frame(
  x = seq(3),
  y = c(1, 3, 9),
  z = c(2, 5, 4),
  w = c(3, 4, 3)
)

plot <- df |>
  e_charts(x) |>
  e_line(z)

expect_s3_class(plot, "echarts4r")
expect_s3_class(plot, "htmlwidget")

expect_equal(
  plot$x$opts$series[[1]]$data,
  list(list(value = c(1, 2)), list(value = c(2, 5)), list(value = c(3, 4)))
)
expect_equal(
  plot$x$opts$series[[1]]$type,
  "line"
)
```

```{r}
# To set-up testthat
# usethis::use_testthat()

# To run all unit tests
# devtools::test()
```
