---
title: "board games"
format: html
embed-resources: true
editor: visual
execute:
  warning: false
---

To set-up testthat
`usethis::use_testthat()`

To run all unit tests or Ctrl-shift-T
`devtools::test()`

To open test script
`usethis::use_test()`

To open R script
`usethis::use_r()`

To change the enviroment
`testthat::local_mocked_bindings()` or {withr}

## Set-up

```{r}
library(dplyr)
# Since this is a notebook, we would need this to render. But since this is a
# package, I'm using load_all()
# source("R/splitColumnByBracket.R")
# source("R/categorizeRatings.R")
# source("R/extractTopNGamesAcrossCols.R")
# source("R/extractTopNGamesByGroup.R")
# source("R/createHorizontalBarChart.R")
```

```{r}
game_ratings <- arrow::read_parquet("data-raw/game_ratings.parquet")
game_details <- arrow::read_parquet("data-raw/game_details.parquet")

games <- left_join(game_ratings, game_details, by = "id")
```

## Data cleaning and recoding

```{r}
# Outputs new cols with boardgamedesigner_clean1, etc
games <- games |> splitColumnByBracket(column_to_split = boardgamedesigner) |> splitColumnByBracket(column_to_split = boardgamemechanic)

# With the function we can use it for 2 columns!
games <- games |>
  dplyr::mutate(average_category = categorizeRatings(average),
                bayes_average_category = categorizeRatings(bayes_average)
                )
```

## Data analysis

```{r}
top_designers_count <- extractTopNGamesAcrossCols(games, start_with_colname = "boardgamedesigner_clean", top_n = 5)

# Look at another column easily!!
top_mechanic_count <- extractTopNGamesAcrossCols(games, start_with_colname = "boardgamemechanic_clean", top_n = 5)

top_games_by_category <- extractTopNGamesByGroup(df = games,
                   group_by_this = average_category,
                   take_max_of_this = users_rated,
                   top_n = 3)
```

## Charts!

```{r}
# Make a chart
top_designers_count |> 
dplyr::arrange(n) |>
createHorizontalBarChart(x_axis = "value", y_axis = "n")

# Make a table
top_games_by_category |>
  dplyr::select(name, average_category) |>
  dplyr::arrange(rev(average_category)) |>
  gt::gt()
```
